server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: "http://localhost:5173"
            allowed-methods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowed-headers: "*"
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=1
        - id: employee-service
          uri: lb://employee-service
          predicates:
            - Path=/api/employee/**
          filters:
            - StripPrefix=1
        - id: attendance-service
          uri: lb://attendance-service
          predicates:
            - Path=/api/attendance/**
          filters:
            - StripPrefix=1
        - id: report-service
          uri: lb://report-service
          predicates:
            - Path=/api/report/**
          filters:
            - StripPrefix=1

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

jwt:
  secret: "wpembytrwcvnryxksdbqwjebruyGHyudqgwveytrtrCSnwifoesarjbwe"
